import { test, expect } from './safe-network'
import { readFileSync } from 'node:fs'
test('priority path: actual video selection, playback, seek and JPEG', async ({ page }) => {
  await page.goto('./')
  await page.locator('input[type=file]').setInputFiles('tests/fixtures/synthetic.webm')
  await expect(page.getByRole('button', { name: '再生', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '再生', exact: true }).click()
  await expect.poll(() => page.locator('video').evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(0)
  await page.getByRole('button', { name: '一時停止', exact: true }).click()
  await page.getByRole('slider', { name: 'タイムライン' }).fill('1.4')
  await expect(page.getByRole('button', { name: 'この場面にする', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'この場面にする', exact: true }).click()
  await expect(page.getByAltText('アドレス', { exact: true })).toBeVisible()
  const pixel = await page.getByAltText('アドレス', { exact: true }).evaluate(async (img: HTMLImageElement) => {
    await img.decode()
    const canvas = document.createElement('canvas'); canvas.width = img.naturalWidth; canvas.height = img.naturalHeight
    const ctx = canvas.getContext('2d')!; ctx.drawImage(img, 0, 0)
    return Array.from(ctx.getImageData(5, 5, 1, 1).data)
  })
  expect(pixel[1]).toBeGreaterThan(150)
  expect(pixel[0]).toBeLessThan(70)
  expect(pixel[2]).toBeLessThan(100)
  expect(pixel[3]).toBe(255)
})

test('empty MIME, cancellation, same-time fallback and rapid actions stay recoverable at mobile width', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.addInitScript(() => {
    Object.defineProperty(HTMLVideoElement.prototype, 'requestVideoFrameCallback', { value: undefined, configurable: true })
  })
  await page.goto('./')
  const input = page.locator('input[type=file]')
  await expect(input).toHaveAttribute('accept', 'video/*')
  expect(await input.getAttribute('multiple')).toBeNull()
  expect(await input.getAttribute('capture')).toBeNull()
  await input.setInputFiles({ name: 'empty-mime.MOV', mimeType: '', buffer: readFileSync('tests/fixtures/synthetic.webm') })
  await expect(page.getByRole('button', { name: 'この場面にする', exact: true })).toBeEnabled()
  await input.setInputFiles([])
  await page.getByRole('slider').fill('1.4')
  const capture = page.getByRole('button', { name: 'この場面にする', exact: true })
  await expect(capture).toBeEnabled()
  await capture.evaluate((button: HTMLButtonElement) => { button.click(); button.click() })
  await expect(page.locator('.frames img')).toHaveCount(1)
  await expect(page.getByAltText('アドレス', { exact: true })).toBeVisible()
  const initial = await page.getByAltText('アドレス', { exact: true }).getAttribute('src')
  await page.getByRole('button', { name: 'アドレスを選ぶ', exact: true }).click()
  await capture.click()
  await expect.poll(() => page.getByAltText('アドレス', { exact: true }).getAttribute('src')).not.toBe(initial)
  await expect(page.locator('.frames')).toContainText('再生位置の代替値')
  await page.getByRole('slider').fill('5')
  await capture.click()
  await expect(page.getByRole('alert')).toContainText('終端')
  await expect(capture).toBeEnabled()
  await page.getByRole('button', { name: '0.1秒戻る', exact: true }).click()
  await expect(page.getByRole('slider')).toHaveValue('4.9')
  await expect(page.getByRole('slider')).toBeEnabled()
  await page.screenshot({ path: 'evidence/editor-mobile-verified.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const sizes = await page.locator('button:visible').evaluateAll(buttons => buttons.map(button => button.getBoundingClientRect().height))
  expect(sizes.every(height => height >= 44)).toBe(true)
  page.once('dialog', dialog => dialog.accept())
  await input.setInputFiles({ name: 'broken.mp4', mimeType: 'video/mp4', buffer: Buffer.from('not a movie') })
  await expect(page.getByRole('alert')).toContainText('読み込めませんでした', { timeout: 20000 })
  page.once('dialog', dialog => dialog.accept())
  await input.setInputFiles('tests/fixtures/synthetic.webm')
  await expect(capture).toBeEnabled()
})
